"""Integration tests for the table-normalization filter (plan items 17, 25)
against tables.docx.

tables.docx (generated by tests/fixtures/make_tables.py) carries a clean
3-column table with a header row and mixed numeric/text columns, plus a
pathological table with a horizontal header merge (gridSpan) and a vertical
body merge (vMerge). The compile-harness tests additionally prove the
emitted body compiles: under a minimal single-column article-class document
(plan item 17's original done-when, now covering the whole body -- item 25
retired the need to slice off the pathological table's section), under a
two-column article (the specific compile wrinkle item 25 had to verify
empirically), and end-to-end through the real ``emit_project`` -> Tectonic
pipeline for every journal (item 25's core done-when) -- all gated on
`@pytest.mark.tectonic`, the same `compile.tectonic.ensure_tectonic()`
pattern as tests/test_pandoc.py.
"""

import shutil
import subprocess
from pathlib import Path

import pytest

from latextify.compile.tectonic import TectonicNotAvailableError, compile_document, ensure_tectonic
from latextify.emit.project import emit_project
from latextify.ingest.pandoc import convert_docx_to_body
from latextify.model import BodyConversionResult
from latextify.templates import loader as templates_loader

FIXTURES = Path(__file__).parent / "fixtures"
TABLES_DOCX = FIXTURES / "tables.docx"


def _copy_fixture(tmp_path: Path, src: Path) -> Path:
    # emit_project's load_meta writes a write-once paper.yaml sidecar BESIDE
    # the docx path it's given -- every emit_project call here must run
    # against a tmp copy, never the committed fixture, or the sidecar lands
    # in tests/fixtures/ (see tests/test_emit.py's module docstring for the
    # same convention).
    dest = tmp_path / src.name
    shutil.copy(src, dest)
    return dest


@pytest.fixture(scope="module")
def tables_result(tmp_path_factory) -> BodyConversionResult:
    media_dir = tmp_path_factory.mktemp("media")
    return convert_docx_to_body(TABLES_DOCX, media_dir)


def test_fixture_exists():
    assert TABLES_DOCX.is_file(), (
        "tests/fixtures/tables.docx is missing -- regenerate with "
        "`uv run python tests/fixtures/make_tables.py`"
    )


def test_returns_body_conversion_result(tables_result):
    assert isinstance(tables_result, BodyConversionResult)


def test_clean_table_converts_to_booktabs(tables_result):
    tex = tables_result.tex
    assert "\\toprule" in tex
    assert "\\midrule" in tex
    assert "\\bottomrule" in tex
    assert "\\begin{tabular}{" in tex
    # No vertical rules anywhere the filter authored a column spec.
    for line in tex.splitlines():
        if line.startswith("\\begin{tabular}{"):
            assert "|" not in line


def test_clean_table_column_alignment_is_content_aware(tables_result):
    # Sample (text) -> left, Temperature (K) (numeric) -> right, Notes
    # (text) -> left.
    tex = tables_result.tex
    assert "\\begin{tabular}{lrl}" in tex


def test_clean_table_rows_present(tables_result):
    tex = tables_result.tex
    assert "Sample & Temperature (K) & Notes \\\\" in tex
    assert "A & 4.2 & superconducting \\\\" in tex
    assert "B & 77 & boiling N2 \\\\" in tex
    assert "C & 300 & room temperature \\\\" in tex


def test_pathological_table_produces_a_finding(tables_result):
    messages = [f.message for f in tables_result.findings]
    assert any(
        "vertically merged cell (vMerge)" in m
        and "verify the structure against the source document" in m
        for m in messages
    )


def test_pathological_table_degrades_to_compilable_booktabs(tables_result):
    # Plan item 25: the pandoc-default rendering (longtable + multirow +
    # \real{}, only defined in pandoc's own --standalone template) doesn't
    # compile in this project's fragment-mode conversion. It's degraded
    # instead to a booktabs table that duplicates the vMerge'd cell's content
    # into every row it spanned -- content survives, merge structure doesn't.
    tex = tables_result.tex
    assert "Measurement" in tex
    assert "\\multirow" not in tex
    assert "\\longtable" not in tex
    assert "\\begin{longtable}" not in tex
    # "10" (the vertically merged cell) duplicated into both rows it spanned.
    assert "1 & 10 & K \\\\" in tex
    assert "2 & 10 & L \\\\" in tex
    assert "[table structure simplified -- verify against source]" in tex


def _tectonic_available() -> bool:
    try:
        ensure_tectonic()
        return True
    except TectonicNotAvailableError:
        return False


@pytest.mark.tectonic
@pytest.mark.skipif(
    not _tectonic_available(),
    reason="no tectonic binary on PATH/cache and none could be downloaded",
)
def test_body_compiles_in_minimal_article_harness(tables_result, tmp_path):
    # Plan item 17's original "Done when": "a tables fixture converts to
    # compiling booktabs output" -- now covering the WHOLE body, clean AND
    # pathological table alike. Item 17 originally had to slice the
    # pathological table's section out of this harness because pandoc's own
    # *default* table writer (which rendered it, untouched, per item 17's
    # original fallback) emits `longtable` + `\multirow` + `\real{}` helper
    # macros that only exist in pandoc's own --standalone template preamble,
    # never in this fragment-mode conversion or any journal manifest here --
    # that gap is plan item 25, fixed by degrading the pathological table to
    # a booktabs reconstruction that needs nothing beyond the `booktabs`
    # already loaded here (see the ingest.filters module docstring's fix
    # (a)-vs-(b) writeup). No more slicing needed.
    harness = (
        "\\documentclass{article}\n"
        "\\usepackage{booktabs}\n"
        "\\begin{document}\n"
        f"{tables_result.tex}\n"
        "\\end{document}\n"
    )
    tex_path = tmp_path / "harness.tex"
    # newline="" -- do NOT let Python's text-mode write translate the "\n"
    # inside pandoc's own "\r\n"-terminated output into a doubled "\r\r\n"
    # on Windows; a longtable-sensitive body turns the resulting phantom
    # blank line into a hard compile error ("Paragraph ended before
    # \LT@array was complete"). Harmless for the plain-paragraph content the
    # existing equations.docx harness test carries, which is why it never
    # surfaced there.
    tex_path.write_text(harness, encoding="utf-8", newline="")

    tectonic_path = ensure_tectonic()
    proc = subprocess.run(
        [str(tectonic_path), "-X", "compile", str(tex_path)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"tectonic failed to compile the harness:\nstdout:\n{proc.stdout}\n"
        f"stderr:\n{proc.stderr}"
    )
    assert (tmp_path / "harness.pdf").is_file()


@pytest.mark.tectonic
@pytest.mark.skipif(
    not _tectonic_available(),
    reason="no tectonic binary on PATH/cache and none could be downloaded",
)
def test_body_compiles_in_two_column_harness(tables_result, tmp_path):
    # The specific wrinkle plan item 25 had to verify empirically rather than
    # assume: `longtable` (pandoc's own default table rendering) is
    # fundamentally incompatible with LaTeX's native `twocolumn` mode --
    # confirmed against a real IEEEtran compile with `Package longtable
    # Error: longtable not in 1-column mode.` (see the ingest.filters module
    # docstring). The degraded booktabs reconstruction here uses a plain
    # `tabular` inside a `table` float, which has no such restriction.
    harness = (
        "\\documentclass[twocolumn]{article}\n"
        "\\usepackage{booktabs}\n"
        "\\begin{document}\n"
        f"{tables_result.tex}\n"
        "\\end{document}\n"
    )
    tex_path = tmp_path / "harness.tex"
    tex_path.write_text(harness, encoding="utf-8", newline="")

    tectonic_path = ensure_tectonic()
    proc = subprocess.run(
        [str(tectonic_path), "-X", "compile", str(tex_path)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"tectonic failed to compile the two-column harness:\nstdout:\n{proc.stdout}\n"
        f"stderr:\n{proc.stderr}"
    )
    assert (tmp_path / "harness.pdf").is_file()


# --------------------------------------------------------------------------- #
# Real end-to-end proof: emit_project -> Tectonic, per journal (plan item 25)
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("journal_name", ["revtex4-2", "ieeetran", "elsarticle", "sn-jnl"])
def test_pathological_table_emits_compilable_body_per_journal(tmp_path, journal_name):
    """``emit_project`` never touches ``longtable``/``multirow`` for a
    pathological table, in every journal: the content survives (duplicated,
    not dropped), the bold in-document note is present, and the finding
    still surfaces as a warning on the ``EmitResult``. Does not compile
    (that's the tectonic-marked tests below) -- this runs unconditionally so
    the content contract is checked even without a Tectonic binary available.
    """
    docx = _copy_fixture(tmp_path, TABLES_DOCX)
    result = emit_project(docx, journal_name, tmp_path / "output", report=False)

    body = result.body_tex_path.read_text(encoding="utf-8")
    assert "Measurement" in body
    assert "\\multirow" not in body
    assert "\\longtable" not in body
    assert "[table structure simplified -- verify against source]" in body

    assert any("vertically merged cell (vMerge)" in w.message for w in result.warnings)


@pytest.mark.tectonic
@pytest.mark.skipif(
    not _tectonic_available(),
    reason="no tectonic binary on PATH/cache and none could be downloaded",
)
@pytest.mark.parametrize("journal_name", ["revtex4-2", "elsarticle", "sn-jnl"])
def test_pathological_table_compiles_end_to_end_per_journal(tmp_path, journal_name):
    """Plan item 25's core done-when: a manuscript containing the
    pathological table (tables.docx) compiles to PDF through the real
    ``emit_project`` -> Tectonic pipeline -- including revtex4-2's two-column
    ``reprint`` mode, which pandoc's own default longtable-based table
    rendering could not have cleared either (see
    ``test_body_compiles_in_two_column_harness`` and the ingest.filters
    module docstring).

    ieeetran is deliberately excluded here and covered instead by
    ``test_ieeetran_real_preamble_compiles_pathological_table`` below: this
    fixture has zero citations, and a genuinely PRE-EXISTING, unrelated bug
    (reproduced independently with the citation-free clean.docx fixture, so
    it is not a tables/item-25 regression) makes ``emit_project``'s
    unconditional ``\\bibliography{references}`` call in ``main.tex`` fail to
    compile against IEEEtran specifically for ANY citation-free manuscript --
    ``LaTeX Error: Something's wrong--perhaps a missing \\item.`` at
    ``\\end{thebibliography}`` in the BibTeX-generated ``main.bbl`` (IEEEtran's
    own ``\\thebibliography`` redefinition does not tolerate zero
    ``\\bibitem``s, unlike revtex4-2/elsarticle/sn-jnl, which all compile fine
    here with the same empty bibliography). Out of scope for item 25 --
    see the executor report.
    """
    docx = _copy_fixture(tmp_path, TABLES_DOCX)
    result = emit_project(docx, journal_name, tmp_path / "output", report=False)

    journal = templates_loader.load(journal_name)
    vendor_dir = journal.root / "vendor" if journal.vendor else None
    compile_result = compile_document(
        result.main_tex_path, tectonic_path=ensure_tectonic(), vendor_dir=vendor_dir
    )
    assert compile_result.success, compile_result.raw_log
    assert compile_result.pdf_path is not None
    assert compile_result.pdf_path.is_file()
    assert compile_result.pdf_path.stat().st_size > 0


@pytest.mark.tectonic
@pytest.mark.skipif(
    not _tectonic_available(),
    reason="no tectonic binary on PATH/cache and none could be downloaded",
)
def test_ieeetran_real_preamble_compiles_pathological_table(tables_result, tmp_path):
    """ieeetran's real preamble (genuine two-column ``journal`` class option,
    exactly as rendered by ``templates.loader``) plus the degraded
    pathological table body -- built directly rather than through
    ``emit_project``, to isolate this from the pre-existing, unrelated
    citation-free-bibliography bug documented in
    ``test_pathological_table_compiles_end_to_end_per_journal`` above (this
    fixture has no citations, so no ``\\bibliography`` call is needed to
    prove the actual thing item 25 is responsible for: the real ieeetran
    twocolumn preamble plus our degraded table compiling together).
    """
    journal = templates_loader.load("ieeetran")
    preamble = journal.render_preamble()
    tex = f"{preamble}\n\\begin{{document}}\n{tables_result.tex}\n\\end{{document}}\n"
    tex_path = tmp_path / "main.tex"
    tex_path.write_text(tex, encoding="utf-8", newline="")

    compile_result = compile_document(tex_path, tectonic_path=ensure_tectonic())
    assert compile_result.success, compile_result.raw_log
    assert compile_result.pdf_path is not None
    assert compile_result.pdf_path.is_file()
    assert compile_result.pdf_path.stat().st_size > 0
