"""Integration tests for latextify.ingest.pandoc against equations.docx.

equations.docx (generated by tests/fixtures/make_equations.py) carries
headings at levels 1-4 and inline + display OMML math. The compile-harness
test additionally proves the emitted body.tex compiles under a minimal
article-class document, using `compile.tectonic.ensure_tectonic()` (binary
detection/download via PATH/cache, not a bare PATH check) -- it is marked
`@pytest.mark.tectonic` per plan item 5, which wired `ensure_tectonic()` in.
"""

import subprocess
from pathlib import Path

import pytest

from latextify.compile.tectonic import TectonicNotAvailableError, ensure_tectonic
from latextify.ingest.pandoc import convert_docx_to_body
from latextify.model import BodyConversionResult

FIXTURES = Path(__file__).parent / "fixtures"
EQUATIONS_DOCX = FIXTURES / "equations.docx"


@pytest.fixture(scope="module")
def equations_result(tmp_path_factory) -> BodyConversionResult:
    media_dir = tmp_path_factory.mktemp("media")
    return convert_docx_to_body(EQUATIONS_DOCX, media_dir)


def test_fixture_exists():
    assert EQUATIONS_DOCX.is_file(), (
        "tests/fixtures/equations.docx is missing -- regenerate with "
        "`uv run python tests/fixtures/make_equations.py`"
    )


def test_convert_docx_to_body_rejects_docx_pandoc_cannot_parse(tmp_path):
    """A .docx with well-formed word/document.xml but missing the surrounding
    OOXML package parts (no [Content_Types].xml) passes preflight's direct
    lxml reads, but pandoc's own docx reader chokes on it -- that must
    surface as a clean, actionable ValueError, never a raw pypandoc
    RuntimeError."""
    import zipfile

    docx_path = tmp_path / "broken_package.docx"
    with zipfile.ZipFile(docx_path, "w") as archive:
        archive.writestr(
            "word/document.xml",
            '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            "<w:body><w:p><w:r><w:t>Hello world</w:t></w:r></w:p></w:body></w:document>",
        )

    with pytest.raises(ValueError, match=r"(?i)pandoc"):
        convert_docx_to_body(docx_path, tmp_path / "media")


def test_returns_body_conversion_result(equations_result):
    assert isinstance(equations_result, BodyConversionResult)
    assert equations_result.media_dir.is_dir()


def test_heading_levels_map_to_section_commands(equations_result):
    tex = equations_result.tex
    assert "\\section{Introduction}" in tex
    assert "\\subsection{Method}" in tex
    assert "\\subsubsection{Results}" in tex
    # Heading 4 ("Too Deep A Section") has no journal-template counterpart
    # and must be clamped to \subsubsection rather than emitted as \paragraph.
    assert "\\subsubsection{Too Deep A Section}" in tex
    assert "\\paragraph{" not in tex
    assert tex.count("\\subsubsection{") == 2


def test_deep_heading_clamp_is_recorded_as_a_finding(equations_result):
    messages = [f.message for f in equations_result.findings]
    assert any("heading level 4" in m and "clamped to 3" in m for m in messages)


def test_math_survives_the_ast_round_trip(equations_result):
    tex = equations_result.tex
    # Inline math ($...$ equivalent)
    assert "\\(\\frac{a}{b}\\)" in tex
    # Display math ($$...$$ equivalent)
    assert "\\[\\frac{a}{b}\\]" in tex


def test_no_unresolved_anchors_in_this_fixture(equations_result):
    # equations.docx has no images/citations; nothing should have been
    # planted, and no stray "%%" markers should appear.
    assert equations_result.figure_count == 0
    assert equations_result.citation_count == 0
    assert "%%" not in equations_result.tex


def _tectonic_available() -> bool:
    try:
        ensure_tectonic()
        return True
    except TectonicNotAvailableError:
        return False


@pytest.mark.tectonic
@pytest.mark.skipif(
    not _tectonic_available(),
    reason="no tectonic binary on PATH/cache and none could be downloaded",
)
def test_body_compiles_in_minimal_article_harness(equations_result, tmp_path):
    harness = (
        "\\documentclass{article}\n"
        "\\usepackage{amsmath}\n"
        "\\begin{document}\n"
        f"{equations_result.tex}\n"
        "\\end{document}\n"
    )
    tex_path = tmp_path / "harness.tex"
    # newline="" stops text-mode translation turning pandoc's CRLF output into
    # \r\r\n on Windows, which TeX reads as phantom blank lines (breaks fragile
    # environments like longtable; harmless for plain paragraphs).
    tex_path.write_text(harness, encoding="utf-8", newline="")

    tectonic_path = ensure_tectonic()
    proc = subprocess.run(
        [str(tectonic_path), "-X", "compile", str(tex_path)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"tectonic failed to compile the harness:\nstdout:\n{proc.stdout}\n"
        f"stderr:\n{proc.stderr}"
    )
    assert (tmp_path / "harness.pdf").is_file()
