"""Integration tests for the table-normalization filter (plan item 17)
against tables.docx.

tables.docx (generated by tests/fixtures/make_tables.py) carries a clean
3-column table with a header row and mixed numeric/text columns, plus a
pathological table with a horizontal header merge (gridSpan) and a vertical
body merge (vMerge). The compile-harness test additionally proves the
emitted booktabs body compiles under a minimal article-class document with
booktabs loaded, using the same `compile.tectonic.ensure_tectonic()` pattern
as tests/test_pandoc.py, gated on `@pytest.mark.tectonic`.
"""

import subprocess
from pathlib import Path

import pytest

from latextify.compile.tectonic import TectonicNotAvailableError, ensure_tectonic
from latextify.ingest.pandoc import convert_docx_to_body
from latextify.model import BodyConversionResult

FIXTURES = Path(__file__).parent / "fixtures"
TABLES_DOCX = FIXTURES / "tables.docx"


@pytest.fixture(scope="module")
def tables_result(tmp_path_factory) -> BodyConversionResult:
    media_dir = tmp_path_factory.mktemp("media")
    return convert_docx_to_body(TABLES_DOCX, media_dir)


def test_fixture_exists():
    assert TABLES_DOCX.is_file(), (
        "tests/fixtures/tables.docx is missing -- regenerate with "
        "`uv run python tests/fixtures/make_tables.py`"
    )


def test_returns_body_conversion_result(tables_result):
    assert isinstance(tables_result, BodyConversionResult)


def test_clean_table_converts_to_booktabs(tables_result):
    tex = tables_result.tex
    assert "\\toprule" in tex
    assert "\\midrule" in tex
    assert "\\bottomrule" in tex
    assert "\\begin{tabular}{" in tex
    # No vertical rules anywhere the filter authored a column spec.
    for line in tex.splitlines():
        if line.startswith("\\begin{tabular}{"):
            assert "|" not in line


def test_clean_table_column_alignment_is_content_aware(tables_result):
    # Sample (text) -> left, Temperature (K) (numeric) -> right, Notes
    # (text) -> left.
    tex = tables_result.tex
    assert "\\begin{tabular}{lrl}" in tex


def test_clean_table_rows_present(tables_result):
    tex = tables_result.tex
    assert "Sample & Temperature (K) & Notes \\\\" in tex
    assert "A & 4.2 & superconducting \\\\" in tex
    assert "B & 77 & boiling N2 \\\\" in tex
    assert "C & 300 & room temperature \\\\" in tex


def test_pathological_table_produces_a_finding(tables_result):
    messages = [f.message for f in tables_result.findings]
    assert any(
        "vertically merged cell (vMerge)" in m and "falling back" in m for m in messages
    )


def test_pathological_table_is_not_silently_reconstructed(tables_result):
    # It must still be present in the emitted body (pandoc's own default
    # table rendering), not dropped or mangled into a booktabs shape it
    # doesn't structurally support.
    tex = tables_result.tex
    assert "Measurement" in tex
    assert "\\multirow" in tex  # pandoc's own vMerge rendering, not ours


def _tectonic_available() -> bool:
    try:
        ensure_tectonic()
        return True
    except TectonicNotAvailableError:
        return False


@pytest.mark.tectonic
@pytest.mark.skipif(
    not _tectonic_available(),
    reason="no tectonic binary on PATH/cache and none could be downloaded",
)
def test_body_compiles_in_minimal_article_harness(tables_result, tmp_path):
    # Only the clean table's own reconstructed output, per plan item 17's
    # "Done when": "a tables fixture converts to compiling booktabs output".
    # The pathological table (kept as-is, past "Instrument Log") is sliced
    # off deliberately: pandoc's own *default* table writer -- which is what
    # renders it, untouched, per the fallback design -- emits column-width
    # helper macros (e.g. ``\real{}``) that only exist in pandoc's own
    # standalone template preamble, not in this fragment-mode conversion or
    # any journal manifest here. That gap is orthogonal to this filter (it
    # would affect any pandoc-default-rendered complex content, not just
    # tables) and is out of scope for item 17 -- see the executor report.
    clean_only_tex = tables_result.tex.split("\\section{Instrument Log}")[0]
    harness = (
        "\\documentclass{article}\n"
        "\\usepackage{booktabs}\n"
        "\\begin{document}\n"
        f"{clean_only_tex}\n"
        "\\end{document}\n"
    )
    tex_path = tmp_path / "harness.tex"
    # newline="" -- do NOT let Python's text-mode write translate the "\n"
    # inside pandoc's own "\r\n"-terminated output into a doubled "\r\r\n"
    # on Windows; a longtable-sensitive body turns the resulting phantom
    # blank line into a hard compile error ("Paragraph ended before
    # \LT@array was complete"). Harmless for the plain-paragraph content the
    # existing equations.docx harness test carries, which is why it never
    # surfaced there.
    tex_path.write_text(harness, encoding="utf-8", newline="")

    tectonic_path = ensure_tectonic()
    proc = subprocess.run(
        [str(tectonic_path), "-X", "compile", str(tex_path)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"tectonic failed to compile the harness:\nstdout:\n{proc.stdout}\n"
        f"stderr:\n{proc.stderr}"
    )
    assert (tmp_path / "harness.pdf").is_file()
