"""Tests for latextify.ingest.preflight.

Fixtures are generated by tests/fixtures/make_unsupported.py and
tests/fixtures/make_clean.py (both committed alongside the .docx files they
produce -- see that README for the fixture corpus policy).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from latextify.ingest.preflight import run_preflight
from latextify.model.preflight import Severity

FIXTURES = Path(__file__).parent / "fixtures"
UNSUPPORTED_DOCX = FIXTURES / "unsupported.docx"
CLEAN_DOCX = FIXTURES / "clean.docx"


@pytest.fixture(scope="module")
def unsupported_report():
    return run_preflight(UNSUPPORTED_DOCX)


@pytest.fixture(scope="module")
def clean_report():
    return run_preflight(CLEAN_DOCX)


def _findings_by_detector(report, detector: str):
    return [f for f in report.findings if f.detector == detector]


# -- one finding per planted construct -------------------------------------


def test_unsupported_docx_yields_one_finding_per_planted_construct(unsupported_report):
    assert len(unsupported_report.findings) == 5
    detectors = sorted(f.detector for f in unsupported_report.findings)
    assert detectors == [
        "equation_as_image",
        "floating_object",
        "smartart",
        "text_box",
        "tracked_changes",
    ]


# -- per-detector tests ------------------------------------------------------


def test_detects_text_box(unsupported_report):
    findings = _findings_by_detector(unsupported_report, "text_box")
    assert len(findings) == 1
    finding = findings[0]
    assert finding.severity is Severity.ERROR
    assert "text box" in finding.location.text_snippet.lower()


def test_detects_tracked_changes(unsupported_report):
    findings = _findings_by_detector(unsupported_report, "tracked_changes")
    assert len(findings) == 1
    finding = findings[0]
    assert finding.severity is Severity.ERROR
    assert "tracked changes" in finding.location.text_snippet.lower()


def test_detects_floating_object(unsupported_report):
    findings = _findings_by_detector(unsupported_report, "floating_object")
    assert len(findings) == 1
    assert findings[0].severity is Severity.WARN


def test_detects_smartart(unsupported_report):
    findings = _findings_by_detector(unsupported_report, "smartart")
    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR


def test_detects_equation_as_image_suspicion(unsupported_report):
    findings = _findings_by_detector(unsupported_report, "equation_as_image")
    assert len(findings) == 1
    finding = findings[0]
    assert finding.severity is Severity.WARN
    assert finding.location.text_snippet.lower().startswith("equation")


def test_findings_report_document_order_locations(unsupported_report):
    # Each planted construct lives in its own paragraph, later than the last.
    indices = [f.location.paragraph_index for f in unsupported_report.findings]
    assert indices == sorted(indices)
    assert len(set(indices)) == len(indices)


# -- clean fixture -----------------------------------------------------------


def test_clean_docx_yields_zero_errors(clean_report):
    assert clean_report.errors == ()
    assert clean_report.has_errors is False


def test_clean_docx_yields_zero_findings(clean_report):
    # Nothing in the clean fixture should trip any detector at all.
    assert clean_report.findings == ()


# -- style inventory -----------------------------------------------------------


def test_clean_docx_style_inventory(clean_report):
    styles = clean_report.styles
    assert styles.heading_levels_used == frozenset({1, 2})
    assert styles.title_style_used is True
    assert styles.caption_style_used is True


def test_unsupported_docx_style_inventory(unsupported_report):
    styles = unsupported_report.styles
    assert styles.heading_levels_used == frozenset({1})
    assert styles.title_style_used is True
    assert styles.caption_style_used is False


# -- report helpers ------------------------------------------------------------


def test_report_warnings_property(unsupported_report):
    warnings = unsupported_report.warnings
    assert {f.detector for f in warnings} == {"floating_object", "equation_as_image"}


def test_report_has_errors_true_when_errors_present(unsupported_report):
    assert unsupported_report.has_errors is True


def test_run_preflight_rejects_non_docx(tmp_path):
    bogus = tmp_path / "not_a_docx.zip"
    import zipfile

    with zipfile.ZipFile(bogus, "w") as archive:
        archive.writestr("hello.txt", "not a word document")

    with pytest.raises(ValueError, match="not a valid .docx"):
        run_preflight(bogus)
