"""Tests for latextify.audit.equations (plan item 23: equation audit tooling).

equations.docx (regenerated by tests/fixtures/make_equations.py for this
item) now carries six equations in document order: an inline fraction, a
display fraction, a display matrix, a display piecewise `cases`, a display
equation array, and a deliberately exotic blank inline placeholder. See that
fixture script's module docstring for provenance of the OMML.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import panflute as pf
import pytest
from typer.testing import CliRunner

from latextify.audit.equations import (
    _compile_audit_pdf,
    extract_equations,
    probe_compile_equations,
    render_audit_markdown,
    write_equation_audit,
)
from latextify.cli import app
from latextify.compile.tectonic import TectonicNotAvailableError, ensure_tectonic
from latextify.model.equations import EquationAuditResult, EquationRecord

FIXTURES = Path(__file__).parent / "fixtures"
EQUATIONS_DOCX = FIXTURES / "equations.docx"


def test_fixture_exists():
    assert EQUATIONS_DOCX.is_file(), (
        "tests/fixtures/equations.docx is missing -- regenerate with "
        "`uv run python tests/fixtures/make_equations.py`"
    )


# --------------------------------------------------------------------------- #
# Corrupt / wrong inputs: clean errors, never a raw traceback
# --------------------------------------------------------------------------- #


def test_extract_equations_rejects_non_docx(tmp_path):
    bogus = tmp_path / "renamed.docx"
    bogus.write_text("This is just plain text, not a docx.\n", encoding="utf-8")

    with pytest.raises(ValueError, match="not a valid .docx"):
        extract_equations(bogus)


def test_extract_equations_rejects_docx_missing_document_xml(tmp_path):
    """A valid zip that isn't OOXML (no word/document.xml) must not leak KeyError."""
    import zipfile

    bogus = tmp_path / "notooxml.docx"
    with zipfile.ZipFile(bogus, "w") as archive:
        archive.writestr("hello.txt", "not a word document")

    with pytest.raises(ValueError, match="not a valid .docx"):
        extract_equations(bogus)


def test_extract_equations_rejects_malformed_document_xml(tmp_path):
    """Malformed XML must not leak a raw lxml.etree.XMLSyntaxError."""
    import zipfile

    bogus = tmp_path / "malformed.docx"
    with zipfile.ZipFile(bogus, "w") as archive:
        archive.writestr("word/document.xml", "<w:document><w:body><w:p>unterminated")

    with pytest.raises(ValueError, match="not a valid .docx"):
        extract_equations(bogus)


@pytest.fixture(scope="module")
def result() -> EquationAuditResult:
    return extract_equations(EQUATIONS_DOCX)


# --------------------------------------------------------------------------- #
# Extraction: counts, order, classification
# --------------------------------------------------------------------------- #


def test_raw_omml_count_matches_fixture(result):
    assert result.raw_omml_count == 6


def test_converted_count_matches_raw_count_no_mismatch(result):
    assert result.converted_count == 6
    assert result.count_mismatch is False


def test_equation_count_and_indices_are_contiguous(result):
    assert len(result.equations) == 6
    assert [e.index for e in result.equations] == [0, 1, 2, 3, 4, 5]


def test_inline_display_classification_in_document_order(result):
    # 0: inline frac, 1: display frac, 2: display matrix, 3: display cases,
    # 4: display eqarray, 5: inline blank placeholder.
    assert [e.display for e in result.equations] == [
        False,
        True,
        True,
        True,
        True,
        False,
    ]


def test_inline_fraction_paired_with_its_paragraph_snippet(result):
    eq = result.equations[0]
    assert eq.latex == "\\frac{a}{b}"
    assert "result follows from" in eq.paragraph_snippet
    assert "shown below" in eq.paragraph_snippet


def test_display_fraction_latex(result):
    assert result.equations[1].latex == "\\frac{a}{b}"


def test_matrix_converts_to_pmatrix_environment(result):
    latex = result.equations[2].latex
    assert "\\begin{pmatrix}" in latex
    assert "\\end{pmatrix}" in latex
    assert "a & b" in latex
    assert "c & d" in latex


def test_cases_converts_to_piecewise_latex(result):
    latex = result.equations[3].latex
    assert "x > 0" in latex
    assert "x \\leq 0" in latex


def test_eqarray_converts_to_aligned_environment(result):
    latex = result.equations[4].latex
    assert "\\begin{aligned}" in latex
    assert "a & = b + c" in latex
    assert "d & = e - f" in latex


def test_exotic_blank_equation_is_inline_and_empty(result):
    eq = result.equations[5]
    assert eq.display is False
    assert eq.latex == ""
    assert "started and abandoned" in eq.paragraph_snippet


# --------------------------------------------------------------------------- #
# Mismatch-flag path (synthetic): pandoc dropping/inventing an equation
# --------------------------------------------------------------------------- #


def test_mismatch_flag_when_pandoc_drops_an_equation(monkeypatch):
    """Simulate pandoc converting fewer equations than the raw OMML walk found."""
    import latextify.audit.equations as audit_equations

    monkeypatch.setattr(
        audit_equations,
        "_pandoc_math_nodes",
        lambda docx_path: [pf.Math("a+b", format="InlineMath")],
    )
    monkeypatch.setattr(
        audit_equations,
        "_walk_raw_equations",
        lambda document_root: [(False, "first"), (True, "second"), (False, "third")],
    )

    out = audit_equations.extract_equations(EQUATIONS_DOCX)

    assert out.raw_omml_count == 3
    assert out.converted_count == 1
    assert out.count_mismatch is True
    # The equation pandoc did convert keeps its real pairing...
    assert out.equations[0].latex == "a+b"
    # ...the ones pandoc dropped get an empty latex rather than a guess.
    assert out.equations[1].latex == ""
    assert out.equations[2].latex == ""
    # Raw-XML snippets are never lost, mismatch or not.
    assert [e.paragraph_snippet for e in out.equations] == ["first", "second", "third"]


def test_mismatch_flag_when_pandoc_invents_an_equation(monkeypatch):
    """Simulate pandoc producing MORE Math nodes than the raw OMML walk found."""
    import latextify.audit.equations as audit_equations

    monkeypatch.setattr(
        audit_equations,
        "_pandoc_math_nodes",
        lambda docx_path: [
            pf.Math("a", format="InlineMath"),
            pf.Math("b", format="DisplayMath"),
        ],
    )
    monkeypatch.setattr(
        audit_equations, "_walk_raw_equations", lambda document_root: [(False, "only one")]
    )

    out = audit_equations.extract_equations(EQUATIONS_DOCX)

    assert out.raw_omml_count == 1
    assert out.converted_count == 2
    assert out.count_mismatch is True
    assert out.equations[0].paragraph_snippet == "only one"
    assert out.equations[0].latex == "a"
    # The "invented" equation has no raw-XML counterpart -- empty snippet,
    # display flag falls back to pandoc's own Math.format classification.
    assert out.equations[1].paragraph_snippet == ""
    assert out.equations[1].latex == "b"
    assert out.equations[1].display is True


def test_no_mismatch_when_counts_agree(monkeypatch):
    import latextify.audit.equations as audit_equations

    monkeypatch.setattr(
        audit_equations,
        "_pandoc_math_nodes",
        lambda docx_path: [pf.Math("x", format="InlineMath")],
    )
    monkeypatch.setattr(
        audit_equations, "_walk_raw_equations", lambda document_root: [(False, "snippet")]
    )

    out = audit_equations.extract_equations(EQUATIONS_DOCX)
    assert out.count_mismatch is False


# --------------------------------------------------------------------------- #
# audit.md structure
# --------------------------------------------------------------------------- #


def test_markdown_header_and_counts(result):
    md = render_audit_markdown(EQUATIONS_DOCX, result)
    assert md.startswith("# Equation Audit — equations.docx")
    assert "**Raw OMML equations found:** 6" in md
    assert "**Pandoc-converted equations:** 6" in md
    assert "MISMATCH" not in md


def test_markdown_lists_every_equation_numbered_one_based(result):
    md = render_audit_markdown(EQUATIONS_DOCX, result)
    for n in range(1, 7):
        assert f"### Equation {n} (" in md


def test_markdown_shows_kind_per_equation(result):
    md = render_audit_markdown(EQUATIONS_DOCX, result)
    assert "### Equation 1 (inline)" in md
    assert "### Equation 2 (display)" in md
    assert "### Equation 6 (inline)" in md


def test_markdown_shows_empty_marker_for_blank_equation(result):
    md = render_audit_markdown(EQUATIONS_DOCX, result)
    assert "**Converted LaTeX:** _(empty)_" in md


def test_markdown_shows_mismatch_banner_when_flagged():
    mismatched = EquationAuditResult(
        equations=(EquationRecord(index=0, display=False, paragraph_snippet="x", latex=""),),
        raw_omml_count=2,
        converted_count=1,
    )
    md = render_audit_markdown(EQUATIONS_DOCX, mismatched)
    assert "MISMATCH" in md
    assert "best-effort" in md


def test_markdown_shows_failed_label_for_failing_equation():
    from latextify.model.equations import EquationCompileStatus

    result_one = EquationAuditResult(
        equations=(
            EquationRecord(index=0, display=True, paragraph_snippet="x", latex="\\frac{a}{"),
        ),
        raw_omml_count=1,
        converted_count=1,
    )
    statuses = (EquationCompileStatus(index=0, ok=False, message="Missing $ inserted"),)
    md = render_audit_markdown(EQUATIONS_DOCX, result_one, compile_statuses=statuses)
    assert "FAILED" in md
    assert "Missing $ inserted" in md
    assert "\\frac{a}{" in md


# --------------------------------------------------------------------------- #
# write_equation_audit (no --pdf): writes equations_audit.md unconditionally
# --------------------------------------------------------------------------- #


def test_write_equation_audit_writes_markdown_without_pdf(tmp_path):
    out = write_equation_audit(EQUATIONS_DOCX, tmp_path, compile_pdf=False)

    assert out.audit_md_path == tmp_path / "equations_audit.md"
    assert out.audit_md_path.is_file()
    assert out.audit_pdf_path is None
    assert out.compile_statuses == ()
    assert out.result.raw_omml_count == 6


def test_write_equation_audit_creates_output_dir(tmp_path):
    nested = tmp_path / "nested" / "audit"
    write_equation_audit(EQUATIONS_DOCX, nested, compile_pdf=False)
    assert (nested / "equations_audit.md").is_file()


# --------------------------------------------------------------------------- #
# CLI smoke tests
# --------------------------------------------------------------------------- #

runner = CliRunner()


def test_cli_equations_writes_audit_md(tmp_path):
    output = tmp_path / "audit"
    cli_result = runner.invoke(
        app, ["equations", str(EQUATIONS_DOCX), "--output", str(output)]
    )

    assert cli_result.exit_code == 0, cli_result.output
    assert (output / "equations_audit.md").is_file()
    assert "wrote" in cli_result.output


def test_cli_equations_missing_docx_exits_nonzero():
    cli_result = runner.invoke(app, ["equations", "does-not-exist.docx"])
    assert cli_result.exit_code != 0


def test_cli_equations_pdf_compile_timeout_is_a_clean_structured_error(tmp_path, monkeypatch):
    """A compile that exceeds its timeout during --pdf must surface as the
    same "error: ..." + nonzero exit every other failure path uses, never a
    raw subprocess.TimeoutExpired traceback (mirrors the `convert` command's
    equivalent guard around compile_document)."""
    import subprocess

    import latextify.audit.equations as audit_equations

    def _fake_compile_document(*args, **kwargs):
        raise subprocess.TimeoutExpired(cmd=["tectonic"], timeout=0.001)

    monkeypatch.setattr(audit_equations, "compile_document", _fake_compile_document)

    output = tmp_path / "audit"
    cli_result = runner.invoke(
        app, ["equations", str(EQUATIONS_DOCX), "--output", str(output), "--pdf"]
    )

    assert cli_result.exit_code != 0
    assert cli_result.exception is None or isinstance(cli_result.exception, SystemExit), (
        f"raw traceback leaked: {cli_result.exception!r}"
    )
    assert "error:" in cli_result.output


def test_cli_equations_pdf_tectonic_present_but_fails_to_execute(tmp_path, monkeypatch):
    """A tectonic binary that exists but can't actually be executed (corrupt
    download, permissions, wrong architecture, ...) raises OSError from
    subprocess.run -- must be a clean error too, not a raw traceback."""
    import latextify.audit.equations as audit_equations

    def _fake_compile_document(*args, **kwargs):
        raise OSError("[WinError 216] This version of %1 is not compatible")

    monkeypatch.setattr(audit_equations, "compile_document", _fake_compile_document)

    output = tmp_path / "audit"
    cli_result = runner.invoke(
        app, ["equations", str(EQUATIONS_DOCX), "--output", str(output), "--pdf"]
    )

    assert cli_result.exit_code != 0
    assert cli_result.exception is None or isinstance(cli_result.exception, SystemExit), (
        f"raw traceback leaked: {cli_result.exception!r}"
    )
    assert "error:" in cli_result.output


def test_cli_equations_default_output_dir_is_equation_audit(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    docx = tmp_path / "equations.docx"
    shutil.copy(EQUATIONS_DOCX, docx)

    cli_result = runner.invoke(app, ["equations", str(docx)])

    assert cli_result.exit_code == 0, cli_result.output
    assert (tmp_path / "equation_audit" / "equations_audit.md").is_file()


# --------------------------------------------------------------------------- #
# Real Tectonic compiles (audit.pdf + per-equation isolation robustness)
# --------------------------------------------------------------------------- #


def _tectonic_available() -> bool:
    try:
        ensure_tectonic()
        return True
    except TectonicNotAvailableError:
        return False


requires_tectonic = pytest.mark.tectonic
skip_without_tectonic = pytest.mark.skipif(
    not _tectonic_available(),
    reason="no tectonic binary on PATH/cache and none could be downloaded",
)


@requires_tectonic
@skip_without_tectonic
class TestRealCompiles:
    def test_audit_pdf_compiles_for_the_fixture(self, tmp_path):
        out = write_equation_audit(EQUATIONS_DOCX, tmp_path, compile_pdf=True)

        assert out.audit_pdf_path is not None, out.audit_md_path.read_text()
        assert out.audit_pdf_path.is_file()
        assert out.audit_pdf_path.stat().st_size > 0
        # Every real equation in this fixture compiles cleanly together, so
        # the fast combined-document path succeeds and no isolated probing
        # is needed -- compile_statuses stays empty.
        assert out.compile_statuses == ()

    def test_cli_equations_pdf_flag_compiles(self, tmp_path):
        output = tmp_path / "audit"
        cli_result = runner.invoke(
            app,
            ["equations", str(EQUATIONS_DOCX), "--output", str(output), "--pdf"],
        )

        assert cli_result.exit_code == 0, cli_result.output
        assert "compiled" in cli_result.output
        assert (output / "audit.pdf").is_file()

    def test_broken_equation_is_isolated_and_marked_failed_not_fatal(self, tmp_path):
        """A single unbalanced-brace equation must not take down the audit --
        it gets isolated by per-equation probing, marked FAILED, and shown as
        raw text so the surrounding equations still compile into audit.pdf."""
        equations = (
            EquationRecord(index=0, display=False, paragraph_snippet="ok one", latex="a + b"),
            EquationRecord(
                index=1, display=True, paragraph_snippet="broken one", latex="\\frac{a}{"
            ),
            EquationRecord(index=2, display=False, paragraph_snippet="ok two", latex="c^2"),
        )

        pdf_path, statuses = _compile_audit_pdf(equations, tmp_path)

        assert pdf_path is not None
        assert pdf_path.is_file()
        by_index = {s.index: s for s in statuses}
        assert by_index[0].ok is True
        assert by_index[1].ok is False
        assert by_index[1].message  # some diagnostic text was captured
        assert by_index[2].ok is True

    def test_probe_compile_equations_isolates_bad_equation_from_good_ones(self, tmp_path):
        equations = (
            EquationRecord(index=0, display=False, paragraph_snippet="ok", latex="x^2"),
            EquationRecord(
                index=1, display=False, paragraph_snippet="bad", latex="\\undefinedmacro{oops}"
            ),
        )
        statuses = probe_compile_equations(equations)
        by_index = {s.index: s for s in statuses}
        assert by_index[0].ok is True
        assert by_index[1].ok is False
