"""Tests for latextify.figures.extract and latextify.figures.override.

figures.docx (generated by tests/fixtures/make_figures.py) carries three
embedded images captioned three different ways -- see that script's
docstring for what each one exercises.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from latextify.figures.extract import extract_figures
from latextify.figures.override import (
    EXTENSION_PRIORITY,
    MANIFEST_FILENAME,
    FigureManifestError,
    describe_source,
    find_override,
    load_manifest,
    resolve_overrides,
)
from latextify.model import Figure, FigureSource

FIXTURES = Path(__file__).parent / "fixtures"
FIGURES_DOCX = FIXTURES / "figures.docx"


def test_fixture_exists():
    assert FIGURES_DOCX.is_file(), (
        "tests/fixtures/figures.docx is missing -- regenerate with "
        "`uv run python tests/fixtures/make_figures.py`"
    )


@pytest.fixture(scope="module")
def figures(tmp_path_factory) -> tuple[Figure, ...]:
    media_dir = tmp_path_factory.mktemp("media")
    return extract_figures(FIGURES_DOCX, media_dir)


# -- media <-> figure-number <-> caption association ------------------------


def test_extracts_three_figures_in_document_order(figures):
    assert [f.number for f in figures] == [1, 2, 3]


def test_all_figures_default_to_embedded_source(figures):
    assert all(f.source is FigureSource.EMBEDDED for f in figures)
    for f in figures:
        assert f.override_path is None
        assert f.resolved_path == f.embedded_path


def test_embedded_paths_point_at_extracted_media_in_document_order(figures):
    names = [f.embedded_path.name for f in figures]
    assert names == ["image1.png", "image2.png", "image3.png"]
    for f in figures:
        assert f.embedded_path.is_file()


def test_caption_style_paragraph_caption_is_captured(figures):
    # Figure 1 uses Word's built-in Caption style; pandoc may promote it into
    # a native Figure block whose own caption already carries the text.
    assert figures[0].caption == (
        "A red placeholder figure, captioned via Word's Caption style."
    )


def test_plain_figure_label_caption_is_captured_via_sibling_fallback(figures):
    # Figure 2's caption is a plain paragraph (no Figure-block promotion),
    # so the caption must come from the adjacent-sibling regex fallback --
    # this is the mitigation for the item 3 finding (pandoc's own \\caption{}
    # can be empty for a promoted Figure block).
    assert figures[1].caption == "A green placeholder figure, captioned via a plain paragraph."


def test_abbreviated_fig_label_is_recognized(figures):
    assert figures[2].caption == "A blue placeholder figure, captioned with the abbreviated label."


def test_caption_label_prefix_is_stripped_not_duplicated(figures):
    # LaTeX's own \caption{} environment prints "Figure N:" itself; the
    # associated caption text must not repeat that label.
    for f in figures:
        assert not f.caption.lower().startswith("figure")
        assert not f.caption.lower().startswith("fig.")


# -- folder-convention override resolution -----------------------------------


def test_extension_priority_order():
    assert EXTENSION_PRIORITY == ("pdf", "eps", "svg", "png", "jpg")


def test_find_override_picks_highest_priority_extension(tmp_path):
    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    (figures_dir / "fig1.png").write_bytes(b"fake-png")
    (figures_dir / "fig1.pdf").write_bytes(b"fake-pdf")
    (figures_dir / "fig1.jpg").write_bytes(b"fake-jpg")

    winner = find_override(figures_dir, 1)
    assert winner == figures_dir / "fig1.pdf"


def test_find_override_returns_none_when_missing(tmp_path):
    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    assert find_override(figures_dir, 1) is None


def test_find_override_returns_none_when_figures_dir_absent(tmp_path):
    assert find_override(tmp_path / "nonexistent", 1) is None


def test_resolve_overrides_is_a_no_op_without_a_figures_directory(figures, tmp_path):
    docx_path = tmp_path / "figures.docx"
    shutil.copy(FIGURES_DOCX, docx_path)

    resolved = resolve_overrides(figures, docx_path)
    assert resolved == figures
    assert all(f.source is FigureSource.EMBEDDED for f in resolved)


def test_override_beside_docx_switches_that_figures_source(figures, tmp_path):
    # Done-when case from plan item 9: dropping figures/fig2.pdf beside the
    # docx switches figure 2's source and the report line says so.
    docx_path = tmp_path / "figures.docx"
    shutil.copy(FIGURES_DOCX, docx_path)
    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    override_file = figures_dir / "fig2.pdf"
    override_file.write_bytes(b"%PDF-1.4 fake override pdf for figure 2\n")

    resolved = resolve_overrides(figures, docx_path)

    by_number = {f.number: f for f in resolved}
    assert by_number[1].source is FigureSource.EMBEDDED
    assert by_number[3].source is FigureSource.EMBEDDED

    fig2 = by_number[2]
    assert fig2.source is FigureSource.OVERRIDE
    assert fig2.override_path == override_file
    assert fig2.resolved_path == override_file
    # Caption association is untouched by override resolution.
    assert fig2.caption == "A green placeholder figure, captioned via a plain paragraph."

    line = describe_source(fig2)
    assert "override" in line
    assert "fig2.pdf" in line
    assert "Figure 2" in line

    embedded_line = describe_source(by_number[1])
    assert "embedded" in embedded_line
    assert "Figure 1" in embedded_line


# -- figures.yaml manifest: parsing + validation (plan item 15) --------------


def test_load_manifest_parses_number_to_relative_path(tmp_path):
    (tmp_path / "custom_fig1.pdf").write_bytes(b"%PDF-1.4 fake\n")
    manifest = tmp_path / MANIFEST_FILENAME
    manifest.write_text("1: custom_fig1.pdf\n", encoding="utf-8")

    resolved = load_manifest(manifest)

    assert resolved == {1: tmp_path / "custom_fig1.pdf"}


def test_load_manifest_relative_path_resolves_against_manifest_directory(tmp_path):
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "vectors" / "fig2.svg").parent.mkdir(parents=True)
    (sub / "vectors" / "fig2.svg").write_text("<svg/>", encoding="utf-8")
    manifest = sub / MANIFEST_FILENAME
    manifest.write_text("2: vectors/fig2.svg\n", encoding="utf-8")

    resolved = load_manifest(manifest)

    assert resolved == {2: sub / "vectors" / "fig2.svg"}


def test_load_manifest_absolute_path_used_as_is(tmp_path):
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()
    absolute_file = elsewhere / "fig3.png"
    absolute_file.write_bytes(b"fake-png")
    manifest_dir = tmp_path / "manuscript"
    manifest_dir.mkdir()
    manifest = manifest_dir / MANIFEST_FILENAME
    manifest.write_text(f"3: {absolute_file.as_posix()}\n", encoding="utf-8")

    resolved = load_manifest(manifest)

    assert resolved == {3: absolute_file}


def test_load_manifest_empty_file_returns_no_entries(tmp_path):
    manifest = tmp_path / MANIFEST_FILENAME
    manifest.write_text("", encoding="utf-8")
    assert load_manifest(manifest) == {}


def test_load_manifest_raises_on_non_mapping_root(tmp_path):
    manifest = tmp_path / MANIFEST_FILENAME
    manifest.write_text("- 1\n- 2\n", encoding="utf-8")

    with pytest.raises(FigureManifestError, match="root must be a mapping"):
        load_manifest(manifest)


@pytest.mark.parametrize("bad_key", ["zero", "-1", "not-a-number", "1.5"])
def test_load_manifest_raises_on_bad_figure_number(tmp_path, bad_key):
    (tmp_path / "fig.pdf").write_bytes(b"fake")
    manifest = tmp_path / MANIFEST_FILENAME
    manifest.write_text(f"{bad_key!r}: fig.pdf\n", encoding="utf-8")

    with pytest.raises(FigureManifestError, match="positive integer"):
        load_manifest(manifest)


def test_load_manifest_raises_on_zero_figure_number(tmp_path):
    (tmp_path / "fig.pdf").write_bytes(b"fake")
    manifest = tmp_path / MANIFEST_FILENAME
    manifest.write_text("0: fig.pdf\n", encoding="utf-8")

    with pytest.raises(FigureManifestError, match="positive integer"):
        load_manifest(manifest)


def test_load_manifest_raises_on_missing_file(tmp_path):
    manifest = tmp_path / MANIFEST_FILENAME
    manifest.write_text("1: does_not_exist.pdf\n", encoding="utf-8")

    with pytest.raises(FigureManifestError, match="does not exist"):
        load_manifest(manifest)


def test_load_manifest_raises_when_path_value_is_not_a_string(tmp_path):
    manifest = tmp_path / MANIFEST_FILENAME
    manifest.write_text("1: 42\n", encoding="utf-8")

    with pytest.raises(FigureManifestError, match="non-empty string"):
        load_manifest(manifest)


# -- manifest resolution beats folder convention (plan item 15 done-when) ----


def test_manifest_beats_folder_convention_on_conflict(figures, tmp_path):
    docx_path = tmp_path / "figures.docx"
    shutil.copy(FIGURES_DOCX, docx_path)

    # Folder-convention override for figure 2 -- would normally win per item 9.
    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    (figures_dir / "fig2.pdf").write_bytes(b"%PDF-1.4 folder override\n")

    # A figures.yaml manifest entry for the SAME figure number, pointing
    # somewhere else entirely -- this must win instead.
    manifest_target = tmp_path / "manifest_fig2.pdf"
    manifest_target.write_bytes(b"%PDF-1.4 manifest override\n")
    (tmp_path / MANIFEST_FILENAME).write_text("2: manifest_fig2.pdf\n", encoding="utf-8")

    resolved = resolve_overrides(figures, docx_path)

    by_number = {f.number: f for f in resolved}
    fig2 = by_number[2]
    assert fig2.source is FigureSource.MANIFEST
    assert fig2.override_path == manifest_target
    assert fig2.resolved_path == manifest_target
    assert fig2.resolved_path != figures_dir / "fig2.pdf"

    # Figures with no manifest entry are untouched by the manifest's presence.
    assert by_number[1].source is FigureSource.EMBEDDED
    assert by_number[3].source is FigureSource.EMBEDDED


def test_manifest_partial_coverage_falls_through_to_folder_then_embedded(figures, tmp_path):
    docx_path = tmp_path / "figures.docx"
    shutil.copy(FIGURES_DOCX, docx_path)

    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    (figures_dir / "fig3.png").write_bytes(b"fake-png-override")

    manifest_target = tmp_path / "manifest_fig1.svg"
    manifest_target.write_text("<svg/>", encoding="utf-8")
    (tmp_path / MANIFEST_FILENAME).write_text("1: manifest_fig1.svg\n", encoding="utf-8")

    resolved = resolve_overrides(figures, docx_path)
    by_number = {f.number: f for f in resolved}

    assert by_number[1].source is FigureSource.MANIFEST
    assert by_number[1].resolved_path == manifest_target
    assert by_number[2].source is FigureSource.EMBEDDED  # no manifest, no folder override
    assert by_number[3].source is FigureSource.OVERRIDE  # folder convention, no manifest entry
    assert by_number[3].resolved_path == figures_dir / "fig3.png"


def test_invalid_manifest_raises_during_resolve_overrides(figures, tmp_path):
    docx_path = tmp_path / "figures.docx"
    shutil.copy(FIGURES_DOCX, docx_path)
    (tmp_path / MANIFEST_FILENAME).write_text("1: nonexistent_file.pdf\n", encoding="utf-8")

    with pytest.raises(FigureManifestError, match="does not exist"):
        resolve_overrides(figures, docx_path)
