"""Tests for latextify.figures.extract and latextify.figures.override.

figures.docx (generated by tests/fixtures/make_figures.py) carries three
embedded images captioned three different ways -- see that script's
docstring for what each one exercises.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from latextify.figures.extract import extract_figures
from latextify.figures.override import (
    EXTENSION_PRIORITY,
    describe_source,
    find_override,
    resolve_overrides,
)
from latextify.model import Figure, FigureSource

FIXTURES = Path(__file__).parent / "fixtures"
FIGURES_DOCX = FIXTURES / "figures.docx"


def test_fixture_exists():
    assert FIGURES_DOCX.is_file(), (
        "tests/fixtures/figures.docx is missing -- regenerate with "
        "`uv run python tests/fixtures/make_figures.py`"
    )


@pytest.fixture(scope="module")
def figures(tmp_path_factory) -> tuple[Figure, ...]:
    media_dir = tmp_path_factory.mktemp("media")
    return extract_figures(FIGURES_DOCX, media_dir)


# -- media <-> figure-number <-> caption association ------------------------


def test_extracts_three_figures_in_document_order(figures):
    assert [f.number for f in figures] == [1, 2, 3]


def test_all_figures_default_to_embedded_source(figures):
    assert all(f.source is FigureSource.EMBEDDED for f in figures)
    for f in figures:
        assert f.override_path is None
        assert f.resolved_path == f.embedded_path


def test_embedded_paths_point_at_extracted_media_in_document_order(figures):
    names = [f.embedded_path.name for f in figures]
    assert names == ["image1.png", "image2.png", "image3.png"]
    for f in figures:
        assert f.embedded_path.is_file()


def test_caption_style_paragraph_caption_is_captured(figures):
    # Figure 1 uses Word's built-in Caption style; pandoc may promote it into
    # a native Figure block whose own caption already carries the text.
    assert figures[0].caption == (
        "A red placeholder figure, captioned via Word's Caption style."
    )


def test_plain_figure_label_caption_is_captured_via_sibling_fallback(figures):
    # Figure 2's caption is a plain paragraph (no Figure-block promotion),
    # so the caption must come from the adjacent-sibling regex fallback --
    # this is the mitigation for the item 3 finding (pandoc's own \\caption{}
    # can be empty for a promoted Figure block).
    assert figures[1].caption == "A green placeholder figure, captioned via a plain paragraph."


def test_abbreviated_fig_label_is_recognized(figures):
    assert figures[2].caption == "A blue placeholder figure, captioned with the abbreviated label."


def test_caption_label_prefix_is_stripped_not_duplicated(figures):
    # LaTeX's own \caption{} environment prints "Figure N:" itself; the
    # associated caption text must not repeat that label.
    for f in figures:
        assert not f.caption.lower().startswith("figure")
        assert not f.caption.lower().startswith("fig.")


# -- folder-convention override resolution -----------------------------------


def test_extension_priority_order():
    assert EXTENSION_PRIORITY == ("pdf", "eps", "svg", "png", "jpg")


def test_find_override_picks_highest_priority_extension(tmp_path):
    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    (figures_dir / "fig1.png").write_bytes(b"fake-png")
    (figures_dir / "fig1.pdf").write_bytes(b"fake-pdf")
    (figures_dir / "fig1.jpg").write_bytes(b"fake-jpg")

    winner = find_override(figures_dir, 1)
    assert winner == figures_dir / "fig1.pdf"


def test_find_override_returns_none_when_missing(tmp_path):
    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    assert find_override(figures_dir, 1) is None


def test_find_override_returns_none_when_figures_dir_absent(tmp_path):
    assert find_override(tmp_path / "nonexistent", 1) is None


def test_resolve_overrides_is_a_no_op_without_a_figures_directory(figures, tmp_path):
    docx_path = tmp_path / "figures.docx"
    shutil.copy(FIGURES_DOCX, docx_path)

    resolved = resolve_overrides(figures, docx_path)
    assert resolved == figures
    assert all(f.source is FigureSource.EMBEDDED for f in resolved)


def test_override_beside_docx_switches_that_figures_source(figures, tmp_path):
    # Done-when case from plan item 9: dropping figures/fig2.pdf beside the
    # docx switches figure 2's source and the report line says so.
    docx_path = tmp_path / "figures.docx"
    shutil.copy(FIGURES_DOCX, docx_path)
    figures_dir = tmp_path / "figures"
    figures_dir.mkdir()
    override_file = figures_dir / "fig2.pdf"
    override_file.write_bytes(b"%PDF-1.4 fake override pdf for figure 2\n")

    resolved = resolve_overrides(figures, docx_path)

    by_number = {f.number: f for f in resolved}
    assert by_number[1].source is FigureSource.EMBEDDED
    assert by_number[3].source is FigureSource.EMBEDDED

    fig2 = by_number[2]
    assert fig2.source is FigureSource.OVERRIDE
    assert fig2.override_path == override_file
    assert fig2.resolved_path == override_file
    # Caption association is untouched by override resolution.
    assert fig2.caption == "A green placeholder figure, captioned via a plain paragraph."

    line = describe_source(fig2)
    assert "override" in line
    assert "fig2.pdf" in line
    assert "Figure 2" in line

    embedded_line = describe_source(by_number[1])
    assert "embedded" in embedded_line
    assert "Figure 1" in embedded_line
